all:
	g++ threads.cpp -o threads.o -pthread -std=c++11 -Wl,--no-as-needed 
	g++ threads_mutex.cpp -o threads_mutex.o -pthread -std=c++11 -Wl,--no-as-needed
	g++ no_threads.cpp -o no_threads.o -std=c++11
